[package]
name = "duck_server"
version = "0.10.0"
authors = ["Patrik Svensson <patrik@patriksvensson.se>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
async-std = { version = "1", features = ["attributes"] }
actix-web = "2"
log = "0.4.8"
